services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: accountdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ef-migrations:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: ef-migrations
    working_dir: /src/AccountDataAccess
    entrypoint: ["/bin/sh", "-c"]
    volumes:
      - .:/src
    environment:
      - CONNECTION_STRING=Host=postgres-db;Port=5432;Database=accountdb;Username=postgres;Password=postgrespwd
    depends_on:
      postgres:
        condition: service_healthy
    command:
      [
        "dotnet restore && dotnet tool install dotnet-ef && dotnet ef database update --connection $CONNECTION_STRING",
      ]
    networks:
      - default

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,lambda,logs
      - PERSISTENCE=0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    working_dir: /tmp/terraform
    entrypoint: ["/bin/sh", "-c"]
    volumes:
      - ./ci/terraform:/src/terraform
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      localstack:
        condition: service_healthy
    command:
      [
        "cp -r /src/terraform/* /tmp/terraform && terraform init && terraform apply -auto-approve",
      ]
    networks:
      - default

  nodejs:
    image: node:24-alpine
    container_name: dynamodb-explorer
    ports:
      - "4567:8001"
    entrypoint: ["/bin/sh", "-c"]
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      terraform:
        condition: service_completed_successfully
    command:
      [
        "npm install -g dynamodb-admin && dynamodb-admin --dynamo-endpoint=http://localstack:4566",
      ]
    networks:
      - default
